const actionTypes = {
	EVENT_TOGGLE_PINNED_STATUS: 'EVENT_TOGGLE_PINNED_STATUS',
	EVENTS_LIST_FETCH_REQUEST: 'EVENTS_LIST_FETCH_REQUEST',
	EVENTS_LIST_FETCH_SUCCESS: 'EVENTS_LIST_FETCH_SUCCESS',
	EVENTS_LIST_FETCH_ERROR: 'EVENTS_LIST_FETCH_ERROR',

	FARMS_LIST_FETCH_REQUEST: 'FARMS_LIST_FETCH_REQUEST',
	FARMS_LIST_FETCH_SUCCESS: 'FARMS_LIST_FETCH_SUCCESS',
	FARMS_LIST_FETCH_ERROR: 'FARMS_LIST_FETCH_ERROR',

	NEWS_FETCH_REQUEST: 'NEWS_FETCH_REQUEST',
	NEWS_FETCH_SUCCESS: 'NEWS_FETCH_SUCCESS',
	NEWS_FETCH_ERROR: 'NEWS_FETCH_ERROR',

	PRODUCTS_LIST_FETCH_REQUEST: 'PRODUCTS_LIST_FETCH_REQUEST',
	PRODUCTS_LIST_FETCH_SUCCESS: 'PRODUCTS_LIST_FETCH_SUCCESS',
	PRODUCTS_LIST_FETCH_ERROR: 'PRODUCTS_LIST_FETCH_ERROR',

	REDUX_STORAGE_LOAD: 'REDUX_STORAGE_LOAD',

	USER_AUTHENTICATION_REQUEST: 'USER_AUTHENTICATION_REQUEST',
	USER_AUTHENTICATION_SUCCESS: 'USER_AUTHENTICATION_SUCCESS',
	USER_AUTHENTICATION_ERROR: 'USER_AUTHENTICATION_ERROR',
	USER_LOGOUT: 'USER_LOGOUT',
};

export default actionTypes;
